Repository parse-community/parse-server, pull requests merged in 2019-07, with the labels that each got.

#5799 Generate sessionToken with linkWith
  spec/ParseUser.spec.js
  src/RestWrite.js
Labels: Merge On Green

#5792 Prepare 3.6.0 Release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#5815 Add contributors section, improve backers section
  README.md
Labels: documentation

#5854 3.7.0 version bump + changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
