Repository parse-community/parse-server, pull requests merged in 2020-02, with the labels that each got.

#5634 Case insensitive signup
  CHANGELOG.md
  spec/MongoStorageAdapter.spec.js
  spec/ParseUser.spec.js
  spec/helper.js
  src/Adapters/Storage/Mongo/MongoCollection.js
  src/Adapters/Storage/Mongo/MongoStorageAdapter.js
  src/Adapters/Storage/Postgres/PostgresStorageAdapter.js
  src/Adapters/Storage/StorageAdapter.js
  src/Controllers/DatabaseController.js
  src/RestWrite.js
Labels: bug, documentation, help wanted

#6431 Fix GraphQL Error Condition on mutation
  src/GraphQL/transformers/mutation.js
Labels: bug

#6360 GraphQL: Allow true GraphQL Schema Customization
  spec/ParseGraphQLServer.spec.js
  src/GraphQL/ParseGraphQLSchema.js
  src/GraphQL/helpers/objectsQueries.js
  src/GraphQL/loaders/defaultRelaySchema.js
  src/GraphQL/loaders/parseClassMutations.js
  src/GraphQL/loaders/parseClassQueries.js
  src/GraphQL/loaders/parseClassTypes.js
  src/ParseServer.js
Labels: enhancement, feature request
