Repository parse-community/parse-server, pull requests merged in 2020-04, with the labels that each got.

#6560 Prep release 4.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#6565 Remove GraphQL Beta Tag
  README.md
Labels: documentation

#6562 Allow to resolve automatically Parse Type fields from Custom Schema
  package.json
  spec/ParseGraphQLServer.spec.js
  src/GraphQL/ParseGraphQLSchema.js
Labels: bug, enhancement

#6651 Allow to unset file from graphql
  spec/ParseGraphQLServer.spec.js
  src/GraphQL/loaders/defaultGraphQLTypes.js
  src/GraphQL/transformers/mutation.js
Labels: enhancement
